# Web Socket Status

#Lobby
WS_STATUS_PLAYER_JOINED = 0
WS_STATUS_PLAYER_LEFT = 1
WS_STATUS_MATCH_STARTED = 2
WS_STATUS_MATCH_ENDED = 3
WS_STATUS_PLAYER_WELCOME = 4

#Partida
WS_STATUS_NEW_TURN = 10
WS_STATUS_DISCARD = 11
WS_STATUS_EXCHANGE_REQUEST = 12
WS_STATUS_EXCHANGE = 13
WS_STATUS_INFECTED = 14
WS_STATUS_DEFENSE_PRIVATE_MSG = 15

#ACCION
WS_STATUS_PLAYER_BURNED = 101
WS_STATUS_CHANGED_OF_PLACES = 102
WS_STATUS_REVERSE_POSITION = 103
WS_STATUS_SUSPECT = 104
WS_STATUS_CARD_DISCOVER = 105
WS_STATUS_CARD_SHOWN = 106
WS_STATUS_ANALYSIS = 107
WS_STATUS_WHISKY = 108
WS_STATUS_SEDUCCION = 109

#DEFENSA
WS_STATUS_HERE_IM_FINE = 201
WS_STATUS_NOTHING_BARBECUE = 202 
WS_STATUS_NOPE_THANKS = 203
WS_STATUS_YOU_FAILED = 204
WS_STATUS_SCARY = 205

# CARD EXCHANGE WS
WS_CARD = 505