# Web Socket Status
WS_STATUS_PLAYER_JOINED = 0
WS_STATUS_PLAYER_LEFT = 1
WS_STATUS_MATCH_STARTED = 2
WS_STATUS_MATCH_ENDED = 3
WS_STATUS_PLAYER_WELCOME = 4
WS_STATUS_NEW_TURN = 5
WS_STATUS_PLAYER_BURNED = 6
WS_STATUS_CHANGED_OF_PLACES = 7
WS_STATUS_REVERSE_POSITION = 8
WS_STATUS_DISCARD = 9
WS_STATUS_SUSPECT = 10
WS_STATUS_CARD_DISCOVER = 11
WS_STATUS_CARD_SHOWN = 12
WS_STATUS_ANALYSIS = 13
WS_STATUS_WHISKY = 14